### PR TITLE
Bug fixes

### LINKED ISSUE #3796: Open With doesn't work
**Describe the bug**
Open With doesn't work for non standard file types. i.e.   .rb (ruby program)

**To Reproduce**
Right click on a file and attempt to open with.

**Expected behaviour**
Open window with options for opening file.

**Screenshots**
https://user-images.githubusercontent.com/24264511/109736632-c882b280-7c18-11eb-8a88-9f1685c7345a.mp4

**Desktop (please complete the following information):**
Edition	Windows 10 Pro
Version	21H1
Installed on	‎28/‎10/‎2020
OS build	19043.844
Experience	Windows Feature Experience Pack 120.2212.3030.0

 - App version: 1.3.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/6072911/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6072912/debug_fulltrust.txt)

### LINKED ISSUE #5652: Pressing Ctrl+Minus makes the filelist zoom out and disappear
### Description

When using Ctrl+Plus/Ctrl+Minus shortcuts to change layout sometimes the filelists zooms out and disappear. Likely due to the fact that Ctrl+Plus/Ctrl+Minus shortcuts are also used by the SemanticZoom control.

### Steps To Reproduce

1. From details view quickly press ctrl+plus and ctrl+minus
2. Click ctrl+minus again
3. Pooof!

### Expected behavior

Files list not going pooof!

### Files Version

Main (1.9.17)

### Windows Version

Versione 1.9.0.0 OS Version: 10.0.19043.1110

### Relevant Assets

https://user-images.githubusercontent.com/9673091/127786925-2c0ef3b0-cae0-4580-8d54-5c1dde5d2434.mp4

### LINKED ISSUE #5667: Rename the First Document Name in Grid View (Medium) Cause Another Files to shift
### Description

Rename the first document's name in Grid View (Medium) will cause another documents to get minimized.

### Steps To Reproduce

1. Surf to a folder which consists more than 1 document
2. Change Layout to Grid View
3. Click on rename (F2) on the very first document

### Expected behavior

Another document(s) should not get minimized.

### Files Version

v1.9.18.0

### Windows Version

Windows 10 21H1 19043.1151

### Relevant Assets

https://user-images.githubusercontent.com/69080584/127991805-1f05117d-fee5-432f-a18b-1d9f070eb5b9.mp4

### LINKED ISSUE #5670: The right click seems not to work on some files without extensions
### Description

Hello,

This morning, trying to open a file with the right click, I noticed a bug. And I don't know if it is referenced, at least I didn't see it so I'm telling you about it.

It's simple, when I right click on a file that has no extension, File only displays a small empty bubble :/

image
image

or when I right-click on a file, and I right-click again on the other one without extension, it opens the menu of the old file where the right-click was done

### Steps To Reproduce

1) Open WSL
2) Go to the desktop for example
3) Write "touch [file name]" in the terminal
4) Open Files and go to the folder where the file was created
5) Right click on it

### Expected behavior

Know how to fix this bug 

### Files Version

1.9.18.0

### Windows Version

Windows 11 Beta Insider - 10.0.22000.100

### Relevant Assets

```markdown
2021-08-03 12:00:41.0097|INFO|OnLaunched|App launched
2021-08-03 12:00:41.6028|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 12:00:41.6697|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 12:00:57.9445|INFO|OnLaunched|App launched
2021-08-03 12:00:58.6197|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 12:00:58.6767|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 12:02:07.3950|INFO|IsRunningOnArm|Running on ARM: False
2021-08-03 12:07:09.1438|INFO|OnLaunched|App launched
2021-08-03 12:07:09.8515|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 12:07:09.9332|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 12:07:11.5669|INFO|IsRunningOnArm|Running on ARM: False
2021-08-03 12:10:32.6747|INFO|OnLaunched|App launched
2021-08-03 12:10:33.3465|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 12:10:33.3933|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 12:17:13.8839|INFO|OnActivated|App activated
2021-08-03 12:17:14.6954|INFO|IsRunningOnArm|Running on ARM: False
2021-08-03 12:17:15.0982|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 12:17:15.4260|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 12:19:12.3599|INFO|OnLaunched|App launched
2021-08-03 12:19:13.0141|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 12:19:13.0990|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 12:19:19.0992|INFO|IsRunningOnArm|Running on ARM: False
2021-08-03 12:27:14.6276|INFO|OnLaunched|App launched
2021-08-03 12:27:15.2821|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 12:27:15.3620|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 12:27:16.7559|INFO|IsRunningOnArm|Running on ARM: False
2021-08-03 12:29:45.8746|INFO|OnLaunched|App launched
2021-08-03 12:29:46.4787|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 12:29:46.5885|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 12:29:49.1583|INFO|IsRunningOnArm|Running on ARM: False
2021-08-03 13:00:47.5910|INFO|OnLaunched|App launched
2021-08-03 13:00:48.3703|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 13:00:48.4243|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 13:00:50.0465|INFO|IsRunningOnArm|Running on ARM: False
2021-08-03 13:16:44.3734|INFO|OnLaunched|App launched
2021-08-03 13:16:45.2388|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 13:16:45.3138|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 13:17:47.3172|INFO|IsRunningOnArm|Running on ARM: False
2021-08-03 13:24:22.1281|INFO|OnLaunched|App launched
2021-08-03 13:24:22.8082|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 13:24:22.8921|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 13:24:24.4888|INFO|IsRunningOnArm|Running on ARM: False
2021-08-03 13:27:37.2586|INFO|OnLaunched|App launched
2021-08-03 13:27:37.9194|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 13:27:37.9945|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 13:27:40.9942|INFO|IsRunningOnArm|Running on ARM: False
2021-08-03 13:30:38.6654|INFO|OnLaunched|App launched
2021-08-03 13:30:39.2537|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 13:30:39.3487|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 13:33:56.4821|INFO|OnLaunched|App launched
2021-08-03 13:33:57.1333|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 13:33:57.2091|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 13:33:58.4109|INFO|IsRunningOnArm|Running on ARM: False
2021-08-03 13:38:51.6739|INFO|OnLaunched|App launched
2021-08-03 13:38:52.2710|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2021-08-03 13:38:52.3483|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2021-08-03 13:38:53.9360|INFO|IsRunningOnArm|Running on ARM: False
2021-08-03 13:39:14.9045|INFO|OnActivated|App activated
```

### LINKED ISSUE #5673: Ctrl + D Keyboard shortcut
### What's the Problem?

_No response_

### Solution/Idea

```markdown
Traditional Windows' File Explorer comes with the ctrl+D keyboard shortcut to delete selected files and folders instead of having to click around with your mouse. This is a very much need feature in my opinion.
```

### Alternatives

```markdown
Currently available alternatives all seem to require mouse usage, which may be undesirable sometimes.
```

### Priorities

```markdown
| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |
```

### Files Version

Versione 1.9.18.0 

### Windows Version

Windows 11 Home 21H2 - 22000.100

### Additional comment

_No response_

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #5670
- Closes #3796
- Closes #5667
- Closes #5673
- Closes #5652

**Details of Changes**
Add details of changes here.
- Fix context menu in case of empty file extension
- Fix open with not working for some file types
- Fix visual glitch when renaming the first element in GridView
- Added Ctrl+D to delete an item to recyclebin (same as explorer)
- Reduced interval for the filesystem watcher, b/c e.g currently it takes 1 second when renaming to see the file updated.
- Disabled SemanticZoom when the filelist is not grouped

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Review by winston-de — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@gave92 thank you!

File: Files/ViewModels/ItemViewModel.cs [hunk 1]
```diff
@@ -1671,14 +1671,14 @@ private async void ProcessOperationQueue(CancellationToken cancellationToken)
             const uint FILE_ACTION_RENAMED_OLD_NAME = 0x00000004;
             const uint FILE_ACTION_RENAMED_NEW_NAME = 0x00000005;
 
-            var sampler = new IntervalSampler(500);
+            var sampler = new IntervalSampler(200);
```
Comment (yaichenbaum) [inline Files/ViewModels/ItemViewModel.cs:1674]: Did you test what kind of performance impact this change has?

Comment (gave92) [reply Files/ViewModels/ItemViewModel.cs:1674]: I've tried pasting and deleting a lot of files from a folder and it seemed alright.
