### PR TITLE
Fixes an issue where the paste menu option didn't always enable

### LINKED ISSUE #2221: Paste option in context menu doesn't always enable
**Describe the bug**
When copying from Windows Explorer to Files, the Paste command in the context menu is disabled until you navigate to a different directory.

**To Reproduce**
1. Open Files and navigation to a directory (i.e. Desktop)
2. Open Windows Explorer, find a file, and copy it
3. Right-click in Files, Paste shows as disabled
4. Navigate to other directory in Files
5. Right-click in Files, Paste now shows as enabled

**Expected behavior**
I expect the Paste command to be enabled

**Screenshots**
image
Copying from Explorer

image
Paste Disabled in Files

image
Now Paste is enabled after navigating to a different directory

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.572
 - App version: v0.18.0.0

**Additional context**
N/A

**Log file**
(There doesn't appear to be anything useful to this bug in the log file)

### PR DESCRIPTION
**Pull request by gave92**
Fixes #2221

### CODE REVIEW

File: Files/ViewModels/CurrentInstanceViewModel.cs [hunk 1]
```diff
@@ -71,28 +76,35 @@ public bool IsPageTypeRecycleBin
...
+                OnPropertyChanged(nameof(CanPasteInPage));
                 OnPropertyChanged(nameof(CanOpenTerminalInPage));
+                OnPropertyChanged(nameof(CanCopyPathInPage));
             }
         }
 
         public bool IsCreateButtonEnabledInPage
         {
-            get => !_IsPageTypeRecycleBin && IsPageTypeNotHome && !_IsPageTypeSearchResults;
+            get => !_IsPageTypeRecycleBin && _IsPageTypeNotHome && !_IsPageTypeSearchResults;
```
Comment (yaichenbaum) [inline Files/ViewModels/CurrentInstanceViewModel.cs:87]:
```suggestion
            get => !isPageTypeRecycleBin && isPageTypeNotHome && !isPageTypeSearchResults;
```

Comment (gave92) [reply Files/ViewModels/CurrentInstanceViewModel.cs:87]: I know they have all the wrong names (this code is old) wanted to keep unnecessary changes to a minimum.
This is pretty small though, I'll do it 👍

Comment (yaichenbaum) [reply Files/ViewModels/CurrentInstanceViewModel.cs:87]: @gave92 Thanks!

**Review by yaichenbaum — APPROVED** [review]
