### PR TITLE
Bugfixes 3

### LINKED ISSUE #5966: Sort by from toolbar always shows sorted by name after restart
### Description

The sort by menu within the sort menu in the toolbar is always showing sorted by name as selected after restart.
The sort by menu within the context menu shows the correct selected sort by option though.

### Steps To Reproduce

_No response_

### Expected behavior

Sort by menu in toolbar to reflect the actually selected sort by option.

### Files Version

Version: 1.9.30.0

### Windows Version

Windows 10 Home 19043.1165

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Fixes for some issues seen on AppCenter
- Closes #5966

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

File: Files/BaseLayout.cs [hunk 1]
```diff
@@ -413,7 +414,7 @@ protected override async void OnNavigatedTo(NavigationEventArgs eventArgs)
                 await ParentShellPageInstance.FilesystemViewModel.SetWorkingDirectoryAsync(navigationArguments.NavPathParam);
 
                 // pathRoot will be empty on recycle bin path
-                var workingDir = ParentShellPageInstance.FilesystemViewModel.WorkingDirectory;
+                var workingDir = ParentShellPageInstance.FilesystemViewModel.WorkingDirectory ?? string.Empty;
```
Comment (gave92) [inline Files/BaseLayout.cs:417]: Could not reproduce.

File: Files/Helpers/UIFilesystemHelpers.cs [hunk 2]
```diff
@@ -231,7 +231,7 @@ public static async Task PasteItemAsync(string destinationPath, IShellPage assoc
             if (packageView && packageView.Result != null)
             {
                 await associatedInstance.FilesystemHelpers.PerformOperationTypeAsync(packageView.Result.RequestedOperation, packageView, destinationPath, false, true);
-                associatedInstance.SlimContentPage.ItemManipulationModel.RefreshItemsOpacity();
+                associatedInstance?.SlimContentPage?.ItemManipulationModel?.RefreshItemsOpacity();
```
Comment (gave92) [inline Files/Helpers/UIFilesystemHelpers.cs:234]: Could not reproduce.

File: Files/Views/MainPage.xaml.cs [hunk 3]
```diff
@@ -282,7 +282,10 @@ private void SidebarControl_SidebarItemInvoked(object sender, SidebarItemInvoked
                     }
             }
 
-            SidebarAdaptiveViewModel.PaneHolder.ActivePane?.NavigateToPath(navigationPath, sourcePageType);
+            if (SidebarAdaptiveViewModel.PaneHolder?.ActivePane is IShellPage shellPage)
+            {
+                shellPage.NavigateToPath(navigationPath, sourcePageType);
```
Comment (gave92) [inline Files/Views/MainPage.xaml.cs:287]: Could not reproduce.

File: Files/Views/ModernShellPage.xaml.cs [hunk 4]
```diff
@@ -403,7 +403,7 @@ private void ModernShellPage_NavigationRequested(object sender, PathNavigationEv
 
         private async void NavigationToolbar_QuerySubmitted(object sender, ToolbarQuerySubmittedEventArgs e)
         {
-            await NavToolbarViewModel.CheckPathInput(e.QueryText, NavToolbarViewModel.PathComponents[NavToolbarViewModel.PathComponents.Count - 1].Path, this);
+            await NavToolbarViewModel.CheckPathInput(e.QueryText, NavToolbarViewModel.PathComponents.LastOrDefault()?.Path, this);
```
Comment (gave92) [inline Files/Views/ModernShellPage.xaml.cs:406]: Could not reproduce.

**Review by gave92 — COMMENTED** [review]
These "fixes" are untested as I could not reproduce the issue, and are more like band-aids than actual solutions. Not sure if it makes sense to include these or not.

File: Files/ViewModels/NavToolbarViewModel.cs [hunk 5]
```diff
@@ -457,6 +457,7 @@ public async void PathBoxItem_DragOver(object sender, DragEventArgs e)
             }
 
             if (!storageItems.Any(storageItem =>
+                !string.IsNullOrEmpty(storageItem?.Path) &&
```
Comment (gave92) [inline Files/ViewModels/NavToolbarViewModel.cs:467]: Could not reproduce.

File: Files/ViewModels/ItemViewModel.cs [hunk 6]
```diff
@@ -1586,6 +1582,7 @@ public async Task<int> EnumerateItemsFromStandardFolderAsync(string path, Type s
                 }
                 else if (hFile.ToInt64() == -1)
                 {
+                    rootFolder ??= await FilesystemTasks.Wrap(() => StorageFileExtensions.DangerousGetFolderFromPathAsync(path));
```
Comment (d2dyno1) [inline Files/ViewModels/ItemViewModel.cs:1585]: `StorageHelpers.ToStorageItem<>()`?

**Review by d2dyno1 — CHANGES_REQUESTED** [review]

File: Files/ViewModels/ItemViewModel.cs (hunk 6 above)
Comment (gave92) [reply Files/ViewModels/ItemViewModel.cs:1585]: Mm I wouldn't call ToStorageItem from inside ItemViewModel as it ends up calling methods inside ItemViewModel itself. Also it calls GetRootFromPathAsync which I don't want in this case.

**Review by d2dyno1 — APPROVED** [review]
Looks good

File: Files/BaseLayout.cs (hunk 1 above)
Comment (d2dyno1) [reply Files/BaseLayout.cs:417]: This one will actually do nothing since `GetPathRoot()` has a failsafe for null or empty strings, and we also check below if the `pathRoot` is null or empty.
