### PR TITLE
Preemptive caching

### LINKED ISSUE #3169: Crashes Upon Load
[debug.txt](https://github.com/files-community/Files/files/5836456/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5836457/debug_fulltrust.txt)

### PR DESCRIPTION
**Pull request by jakoss**
Adds preemptive caching to #1769
Fixes #3169

I had to do some refactoring to implement this feature. I had to make the "enumeration" functions more independent of `ItemViewModel`. I moved out some methods out of viewmodel, just for sake of readability and just to be a little more SOLID. I managed to lower `ItemViewModel` line count by 200.

There's one question from me. What is the reason to keep Win32 files enumeration along with Windows.Storage? I measured a little bit and i used application with only Windows.Storage enumeration and i didn't found significant performance difference. All gains from using direct C++ apis are minimal compared to other required operations in `EnumerateItemsFromStandardFolderAsync`. So i believe that using that introduces a lot of complicated and doubled logic without any real gain.  @yair100 @gave92 What do you think about that?

I'll tackle the "double loading" issue in next Pull Request.

### CODE REVIEW

**Comment by gave92** [comment]
Windows.Storage does not lost shortcut files and hidden items

File: Files/Filesystem/StorageEnumerators/UniversalStorageEnumerator.cs [hunk 1]
```diff
@@ -0,0 +1,268 @@
...
+                {
+                    break;
+                }
+                catch (Exception ex) when (
+                    ex is UnauthorizedAccessException
+                    || ex is FileNotFoundException
+                    || (uint)ex.HResult == 0x80070490) // ERROR_NOT_FOUND
+                {
+                    // If some unexpected exception is thrown - enumerate this folder file by file - just to be sure
+                    items = await EnumerateFileByFile(rootFolder, count, maxItemsToRetrieve);
```
Comment (jakoss) [inline Files/Filesystem/StorageEnumerators/UniversalStorageEnumerator.cs:64]: @gave92 As per our discussion - i'm using batch file loading and falling back to file by file only in case of exception here

File: Files/ViewModels/ItemViewModel.cs [hunk 2]
```diff
@@ -806,10 +802,45 @@ public async void RapidAddItemsToCollectionAsync(string path, string previousDir
...
+                                    if (Path.IsPathRooted(path))
+                                    {
+                                        var res = await FilesystemTasks.Wrap(() => StorageFileExtensions.DangerousGetFolderWithPathFromPathAsync(path, null, parentFolder: currentStorageFolderSnapshot));
+                                        if (res)
+                                        {
+                                            storageFolder = res.Result;
+                                        }
+                                    }
+                                    await EnumerateItemsFromStandardFolderAsync(path, storageFolder, sourcePageType, _addFilesCTS.Token, cacheOnly: true);
+                                }, maxDegreeOfParallelism: 5);
```
Comment (jakoss) [inline Files/ViewModels/ItemViewModel.cs]: @gave92 @yair100 I setup 5 as a start, but i believe this should be an option in settings?

Comment (yaichenbaum) [reply Files/ViewModels/ItemViewModel.cs:835]: @jakoss What does this number control?

**Comment by jakoss** [comment]
> Windows.Storage does not list shortcut files and hidden items
> And Win32 does not work on phone storage (and network?)

Ok, so removing that is not an option

**Comment by gave92** [comment]
And none of those work on recycle bin xD yeah it's complicated

File: Files/ViewModels/ItemViewModel.cs (hunk 2 above)
Comment (jakoss) [reply Files/ViewModels/ItemViewModel.cs:835]: On every navigation i'm running preemptive caching on child folders. This numbers controls the number of folders to cache in parallel. The larger the number - the more disc and cpu usage user can see

Comment (yaichenbaum) [reply Files/ViewModels/ItemViewModel.cs:835]: 5 seems like a good start, there should probably be a setting though.

Comment (jakoss) [reply Files/ViewModels/ItemViewModel.cs]: I added new setting. PR is ready for review

File: Files/Views/SettingsPages/Experimental.xaml [hunk 3]
```diff
@@ -45,6 +46,16 @@
...
+
+                <controls:NumberBox 
+                    x:Uid="PreemptiveCacheParallelLimits"
+                    HorizontalAlignment="Left"
+                    Header="Preemptive cache parallel limit (0 turns off the preemptive cache)" 
+                    FontSize="17"
+                    SpinButtonPlacementMode="Inline"
+                    Width="300"
+                    Value="{Binding PreemptiveCacheParallelLimit, Mode=TwoWay}" 
+                    Minimum="0" />
```
Comment (yaichenbaum) [inline Files/Views/SettingsPages/Experimental.xaml:58]:
```suggestion
                    Minimum="0" 
                    HeaderTemplate="{StaticResource CustomHeaderStyle}"
                    IsEnabled="{Binding UseFileListCache, Mode=OneWay}"/>
```

**Review by yair100 — COMMENTED** [review]
@jakoss It seems like the NumberBox Header is skipped over by the screen reader, can you check that out?

File: Files/Views/SettingsPages/Experimental.xaml (hunk 3 above)
Comment (jakoss) [reply Files/Views/SettingsPages/Experimental.xaml:59]: The issue with screen reader seems to be rooted in WinUI library. I didn't found such bug for NumberBox specificaly, but there are quite such bugs for other controls, like radio buttons: https://github.com/microsoft/microsoft-ui-xaml/issues/3183

I'm not quite sure what to do here

Comment (yaichenbaum) [reply Files/Views/SettingsPages/Experimental.xaml]: If there was one person who would know, it would probably be @chingucoding 😂

File: Files/Views/SettingsPages/Experimental.xaml [hunk 4]
```diff
@@ -45,7 +46,20 @@
...
+                    x:Uid="PreemptiveCacheParallelLimits"
+                    HorizontalAlignment="Left"
+                    Header="Preemptive cache parallel limit (0 turns off the preemptive cache)" 
+                    SpinButtonPlacementMode="Inline"
+                    Width="450"
+                    Value="{Binding PreemptiveCacheParallelLimit, Mode=TwoWay}" 
+                    HeaderTemplate="{StaticResource CustomHeaderStyle}"
+                    IsEnabled="{Binding UseFileListCache, Mode=OneWay}"
+                    Minimum="0" 
+                    HeaderTemplate="{StaticResource CustomHeaderStyle}"
```
Comment (jakoss) [inline Files/Views/SettingsPages/Experimental.xaml]: @yair100 I already did that change, so we have a duplicates here

File: Files/Views/SettingsPages/Experimental.xaml (hunk 3 above)
Comment (chingucoding) [reply Files/Views/SettingsPages/Experimental.xaml]: What exactly is the question here?

File: Files/Views/SettingsPages/Experimental.xaml (hunk 4 above)
Comment (yaichenbaum) [reply Files/Views/SettingsPages/Experimental.xaml:60]: Whoops, sorry about that!

File: Files/Views/SettingsPages/Experimental.xaml (hunk 3 above)
Comment (yaichenbaum) [reply Files/Views/SettingsPages/Experimental.xaml]: @chingucoding for some reason the header of the number box isn't read by the screen reader.

File: Files/Views/SettingsPages/Experimental.xaml [hunk 5]
```diff
@@ -45,7 +46,20 @@
...
+
+                <controls:NumberBox 
+                    x:Uid="PreemptiveCacheParallelLimits"
+                    HorizontalAlignment="Left"
+                    Header="Preemptive cache parallel limit (0 turns off the preemptive cache)" 
+                    SpinButtonPlacementMode="Inline"
+                    Width="450"
+                    Value="{Binding PreemptiveCacheParallelLimit, Mode=TwoWay}" 
+                    HeaderTemplate="{StaticResource CustomHeaderStyle}"
+                    IsEnabled="{Binding UseFileListCache, Mode=OneWay}"
```
Comment (yaichenbaum) [inline Files/Views/SettingsPages/Experimental.xaml:58]:
```suggestion
```

File: Files/Views/SettingsPages/Experimental.xaml (hunk 3 above)
Comment (chingucoding) [reply Files/Views/SettingsPages/Experimental.xaml]: This is a known issue with NumberBox and the fact that it wraps around a TextBox which conflict with each other. See https://github.com/microsoft/microsoft-ui-xaml/issues/3505 and the fixing PR https://github.com/microsoft/microsoft-ui-xaml/pull/3775 for more context.

Comment (yaichenbaum) [reply Files/Views/SettingsPages/Experimental.xaml]: Thanks! I guess this will be fixed in one of the next WinUI releases so it's nothing to worry about.

File: Files/Views/SettingsPages/Experimental.xaml [hunk 6]
```diff
@@ -45,7 +46,18 @@
...
+                <controls:NumberBox 
+                    x:Uid="PreemptiveCacheParallelLimits"
+                    HorizontalAlignment="Left"
+                    Header="Preemptive cache parallel limit (0 turns off the preemptive cache)" 
+                    SpinButtonPlacementMode="Inline"
+                    Width="450"
+                    Value="{Binding PreemptiveCacheParallelLimit, Mode=TwoWay}" 
+                    Minimum="0" 
+                    HeaderTemplate="{StaticResource CustomHeaderStyle}"
+                    IsEnabled="{Binding UseFileListCache, Mode=OneWay}"/>
```
Comment (yaichenbaum) [inline Files/Views/SettingsPages/Experimental.xaml:59]: Would you be able to create a page on the [documentation ](https://github.com/files-community/files-community.github.io/blob/main/docs) site explaining how this works?

Comment (jakoss) [reply Files/Views/SettingsPages/Experimental.xaml:59]: Sure, i'll create performance article there

Comment (jakoss) [reply Files/Views/SettingsPages/Experimental.xaml:59]: https://github.com/files-community/files-community.github.io/pull/23

**Review by yair100 — DISMISSED** [review]

File: Files/ViewModels/SettingsViewModel.cs [hunk 7]
```diff
@@ -607,6 +607,15 @@ public bool UseFileListCache
             set => Set(value);
         }
 
+        /// <summary>
+        /// Gets or sets a value indicating the limit of parallel preemptive cache loading limit.
+        /// </summary>
+        public int PreemptiveCacheParallelLimit
+        {
+            get => Get(5);
```
Comment (gave92) [inline Files/ViewModels/SettingsViewModel.cs:615]: Enabled by default is ok @yaichenbaum?

**Review by gave92 — CHANGES_REQUESTED** [review]
I love the ItemViewModel refactoring :)

An issue I'm seeing is that with this option enabled folder switching is sometimes delayed (I'll try to post a video). Is it just me?

File: Files/Strings/en-US/Resources.resw [hunk 8]
```diff
@@ -1554,6 +1554,9 @@
   <data name="SettingsUseFileListCache.Header" xml:space="preserve">
     <value>Cache files and folders for better performance</value>
   </data>
+  <data name="PreemptiveCacheParallelLimit.Header" xml:space="preserve">
```
Comment (gave92) [inline Files/Strings/en-US/Resources.resw:1557]: Why am I not seeing this resource added to all .xlf files?

Comment (yaichenbaum) [reply Files/Strings/en-US/Resources.resw:1557]: It's actually preferred to let one of us do it when before submitting it to the store, this will prevent potential merge conflicts that are difficult to solve.

File: Files/ViewModels/SettingsViewModel.cs (hunk 7 above)
Comment (yaichenbaum) [reply Files/ViewModels/SettingsViewModel.cs:615]: That's fine, after testing it out, I think we should lower it a bit since it's a little heavy on system resources.

File: Files/ViewModels/ItemViewModel.cs [hunk 9]
```diff
@@ -1096,203 +1134,101 @@ public async Task<bool> EnumerateItemsFromStandardFolderAsync(string path)
                     FileSize = null,
                     FileSizeBytes = 0
                 };
+                if (!cacheOnly)
```
Comment (gave92) [inline Files/ViewModels/ItemViewModel.cs:1137]: Missing "{" for code style

File: Files/ViewModels/SettingsViewModel.cs (hunk 7 above)
Comment (jakoss) [reply Files/ViewModels/SettingsViewModel.cs:615]: I think it might be good to consider different values for different drive type

**Comment by jakoss** [comment]
Wow, commit `c38ef5cee5dd72b0aab11fbd15f0e43d662e6006` was a killer merge for me

**Comment by yaichenbaum** [comment]
@jakoss What's the current status with this PR?

**Comment by jakoss** [comment]
Sorry, I had busy week. I need to merge hez2010 changes in here and that will take me some time. I'll try to do this sometime next week

**Comment by yaichenbaum** [comment]
> Sorry, I had busy week. I need to merge hez2010 changes in here and that will take me some time. I'll try to do this sometime next week

It's no rush, thank you for the update.

**Comment by jakoss** [comment]
@yair100 @gave92 I merged the changes from main branch, it was quite a ride after @hez2010 PR. But i think i got it right. Not sure about the end result after all. It does speed up things on my computer, but i have only nvme drives to test that on. And even on those the speedup is not really that mindblowing. Try it out on your machines.

Also there are minor changes to `PersistentSQLiteCacheAdapter` that should resolve the https://github.com/files-community/Files/issues/3169

I also made the adjustement to cache only the first 32 loaded items, since it's all we need to "visually" improve loading time.

File: Files/ViewModels/SettingsViewModel.cs (hunk 7 above)
Comment (yaichenbaum) [reply Files/ViewModels/SettingsViewModel.cs:645]: > I think it might be good to consider different values for different drive type

That might be a good way to do it, I would also consider changing this option into an on/off switch instead of letting the user choose the actual value.

Comment (jakoss) [reply Files/ViewModels/SettingsViewModel.cs:645]: Do you have some tested way to check for the drive type in UWP?

Comment (yaichenbaum) [reply Files/ViewModels/SettingsViewModel.cs:645]: @jakoss Not that I know of, perhaps we should stick with a lower number for now and if we find a way to detect the drive type, we can adjust it later on.

Comment (jakoss) [reply Files/ViewModels/SettingsViewModel.cs:662]: Ok, i lowered this to 2 (i think it's better to target hard drives for now)

Comment (jakoss) [reply Files/ViewModels/SettingsViewModel.cs]: I adjusted the settings (new on/off switch). I think PR is ready for review and merge

Comment (yaichenbaum) [reply Files/ViewModels/SettingsViewModel.cs]: Should we remove the setting to adjust the limit and just have the option to turn it on or off?

Comment (jakoss) [reply Files/ViewModels/SettingsViewModel.cs]: I think it's fine the way it is now. On/off switch is independent of limit setting. Limit selector will be enabled only if caching and preemptive caching are on. Users with fast ssd drives can bump this up. Minimum is 1

**Review by yair100 — DISMISSED** [review]

**Comment by gave92** [comment]
[DO NOT MERGE] Latest commit solves merge conflicts with main but looses change from (at least)  #3123, #3561

**Review by gave92 — DISMISSED** [review]

**Comment by gave92** [comment]
@jakoss I updated this PR with the latest changes from main. I hope I haven't screwed anything up.

File: Files/ViewModels/SettingsViewModel.cs [hunk 10]
```diff
@@ -671,10 +671,28 @@ public bool ShowFileOwner
         /// </summary>
         public bool UseFileListCache
         {
-            get => Get(true);
+            get => Get(false);
```
Comment (yaichenbaum) [inline Files/ViewModels/SettingsViewModel.cs:674]:
```suggestion
            get => Get(true);
```

**Review by yair100 — CHANGES_REQUESTED** [review]

**Review by yair100 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@jakoss Thank you!
