### PR TITLE
Fixed crashes when opening properties dialog

### LINKED ISSUE #4591: Crash when opening library properties
**Explain the bug**
For some libraries, opening the properties window will cause a crash.

**To reproduce**
1. Go to home page
2. Right click a library widget
3. See crash

alternatively 

1. Right click library in sidebar
2. Open properties
3. See crash

**Expected behavior**
Properties for libraries should open normally.

**Logfile**
```
2021-04-11 19:36:58.1643|ERROR|.ctor|Invalid pointer

Object reference not set to an instance of an object.|System.NullReferenceException: Invalid pointer

Object reference not set to an instance of an object.
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32, Void*, Void*) + 0x48
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler__Impl.Invoke(__ComObject, Object, NotifyCollectionChangedEventArgs) + 0xb0
   at System.Action`2.InvokeClosedStaticThunk(T1, T2) + 0x2e
   at System.Action`2.InvokeMulticastThunk(T1, T2) + 0x4e
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs) + 0x2b
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedAction, Object, Int32) + 0x47
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32, T) + 0x6c
   at Files.ViewModels.MainPageViewModel.<AddNewTabByPathAsync>d__34.MoveNext() + 0x262
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at Files.ViewModels.MainPageViewModel.<OnNavigatedTo>d__37.MoveNext() + 0x720
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
   at __Interop.ForwardComStubs.Stub_19[TThis](__ComObject, Int32) + 0x24
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x3d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x75
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__24[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0x15b56a0
```

**Screenshots**

https://user-images.githubusercontent.com/59544401/114646256-ca1bad80-9c8f-11eb-855d-ad148ddefea4.mp4

**System Information**
 - OS Version: 19043.906
 - App version: 1.5.9.0

**Additional comment**

### LINKED ISSUE #4628: Opening drive properties causes crash
**Explain the bug**
Files crashes when opening drive properties from a drive widget context menu.

**To reproduce**
1. Go to home page
2. right click drive
3. open properties
4. see crash

**Logfile**
```
The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E)|System.Exception: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E)
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32, Void*) + 0xbe
   at __Interop.ForwardComStubs.Stub_9[TThis, TArg0](__ComObject, TArg0, Int32) + 0x5a
   at Files.UserControls.FileIcon.FileIcon_obj1_Bindings.Update_ViewModel_CustomIcon(SvgImageSource, Int32) + 0x3a
   at Files.UserControls.FileIcon.FileIcon_obj1_Bindings.Update_ViewModel(SelectedItemsPropertiesViewModel, Int32) + 0x7a
   at Files.UserControls.FileIcon.FileIcon_obj1_Bindings.Update() + 0x33
   at Files.UserControls.FileIcon.FileIcon_obj1_Bindings.Loading(FrameworkElement, Object) + 0xe
   at Microsoft.Toolkit.Uwp.UI.Controls.InAppNotificationOpeningEventHandler.Invoke(Object, InAppNotificationOpeningEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__24[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0x16398ce
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
   at __Interop.ForwardComStubs.Stub_19[TThis](__ComObject, Int32) + 0x24
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x3d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x75
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__24[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0x16291e0
```

**Additional comment**
The property marshalled for a different thread seems to be ```SelectedItemsPropertiesViewModel```.

### LINKED ISSUE #4639: App crash when opening properties
**Explain the bug**
When I try opening properties of a drive it will crash instantly. When doing it for folders it will open but crash when I press cancel (why is that there in the first place) the properties.

**Expected behaviour**
Open properties of the folder or drive

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6326666/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6326667/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5.13

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**
Itemize resolved / related issues by this PR.
- Closes #4639 
- closes #4628 
- closes #4591

**Details of Changes**
Add details of changes here.
- Remove all calls to ImageSource properties in the properties dialog as they are not thread safe and would cause a crash
- obtain images from uri source or byte array

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility (Not applicable) 

**Screenshots (optional)**
image

### CODE REVIEW

File: Files/DataModels/SidebarPinnedModel.cs [hunk 1]
```diff
@@ -265,7 +265,8 @@ public async Task AddItemToSidebarAsync(string path)
                     Font = InteractionViewModel.FontName,
                     Path = path,
                     Section = SectionType.Favorites,
-                    Icon = GlyphHelper.GetIconUri(path),
+                    Icon = new Windows.UI.Xaml.Media.Imaging.SvgImageSource(GlyphHelper.GetIconUri(path)),
```
Comment (yaichenbaum) [inline Files/DataModels/SidebarPinnedModel.cs:268]: We are going to start using regular system thumbnails for the sidebar, does it make sense to make this change being that it might not be an SVG source anymore?

Comment (winston-de) [reply Files/DataModels/SidebarPinnedModel.cs:268]: I think we should keep it for now, we can always remove it after we switch to the system icons

**Review by yaichenbaum — APPROVED** [review]
