### PR TITLE
Fixed issue where previewing folder shortcut would cause a crash

### LINKED ISSUE #3978: Preview pane:  Crash when clicking on a folder shortcut
**1-** Enable preview pane

**2-** Click on a folder shortcut

**3-** Crash

crash

**Log:**
`2021-03-11 13:19:36.3294|ERROR|Files.App|Acceso denegado. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))|System.UnauthorizedAccessException: Acceso denegado. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Files.ViewModels.Previews.FolderPreviewViewModel.LoadPreviewAndDetailsAsync()
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
`

### PR DESCRIPTION
**Pull request by winston-de**
Closes #3978 

This fix should work fine, but shortcuts aren't working for me at all, so if someone could test this I would greatly appreciate it.

### CODE REVIEW

File: Files/ViewModels/Previews/FolderPreviewViewModel.cs [hunk 1]
```diff
@@ -22,10 +22,20 @@ public class FolderPreviewViewModel
         public FolderPreviewViewModel(ListedItem item)
         {
             Item = item;
-            LoadPreviewAndDetailsAsync();
         }
 
-        private async void LoadPreviewAndDetailsAsync()
+        public async Task Load()
```
Comment (gave92) [inline Files/ViewModels/Previews/FolderPreviewViewModel.cs:27]: Looks good. I'd only change this to: `public async Task LoadAsync()`

**Review by gave92 — APPROVED** [review]

**Review by gave92 — APPROVED** [review]

**Comment by gave92** [comment]
> Shortcuts aren't working for me at all

Please tell me you're on a windows insider build :)

**Comment by winston-de** [comment]
> > Shortcuts aren't working for me at all
> 
> Please tell me you're on a windows insider build :)

@gave92 yup xD

**Review by emad70 — APPROVED** [review]
