### PR TITLE
Fixed invalid items from being added to bundles

### LINKED ISSUE #6974: Cannot open a directory which name include "." from Bundles Widget
### Description

Cannot open a directory which name include "." from Bundles Widget
No response after click

### Steps To Reproduce

1. Create a directory which the name include "."  `qwer.asdf`
2. Add directory to bundles widget
3. Restart the software
4. Open the directory from the bundles widget

### Expected behavior

Click the directory in the bundles widget to open it

### Files Version

v2.0.36.0

### Windows Version

Windows 11 10.0.22499.1010

### Relevant Assets

https://user-images.githubusercontent.com/32838371/142268376-730662bb-334d-4626-a000-c8acdedd658c.mp4

### PR DESCRIPTION
**Pull request by d2dyno1**
**Resolved / Related Issues**
- Closes #6974

**Details of Changes**
- This PR replaces the old `ToStorageItem()` function with a newer and faster one from Clipboard Canvas.

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

File: Files/Helpers/StorageItemHelpers.cs [hunk 1]
```diff
@@ -30,39 +31,49 @@ public static async Task<IStorageItem> ToStorageItem(this IStorageItemWithPath i
                 // for now, we can't
                 return default;
             }
-            else if (typeof(IStorageFile).IsAssignableFrom(typeof(TOut)))
+
+            // Fast get attributes
+            bool exists = NativeFileOperationsHelper.GetFileAttributesExFromApp(path, NativeFileOperationsHelper.GET_FILEEX_INFO_LEVELS.GetFileExInfoStandard, out NativeFileOperationsHelper.WIN32_FILE_ATTRIBUTE_DATA itemAttributes);
```
Comment (gave92) [inline Files/Helpers/StorageItemHelpers.cs:36]: I'm afraid this might fail on: phone storage, networks shares, zip files, ftp.. could you check?

Comment (d2dyno1) [reply Files/Helpers/StorageItemHelpers.cs:36]: Indeed it does, I'll try to workaround it

Comment (d2dyno1) [reply Files/Helpers/StorageItemHelpers.cs:36]: @gave92 Do you have any win32 function we could use to determine the file type? I'm out of ideas

Comment (gave92) [reply Files/Helpers/StorageItemHelpers.cs:36]: My suggestion is you do the reverse: _if_ GetFileAttributesExFromApp _succeedes_ then you use it to check if it's a file or folder, if id does not succeed keep current behaviour. It will still be faster in 90% of cases.

Comment (d2dyno1) [reply Files/Helpers/StorageItemHelpers.cs:36]: Seems like a good idea 💡

File: Files/Helpers/StorageHelpers.cs [hunk 2]
```diff
@@ -11,58 +11,93 @@ namespace Files.Helpers
...
         }
 
-        public static async Task<TOut> ToStorageItem<TOut>(string path, IShellPage associatedInstance = null) where TOut : IStorageItem
+        public static async Task<TRequested> ToStorageItem<TRequested>(string path, IShellPage associatedInstance = null) where TRequested : IStorageItem
         {
             FilesystemResult<BaseStorageFile> file = null;
             FilesystemResult<BaseStorageFolder> folder = null;
 
-            if (path.ToLowerInvariant().EndsWith(".lnk", StringComparison.Ordinal) || path.ToLowerInvariant().EndsWith(".url", StringComparison.Ordinal))
+            if (path.ToLowerInvariant().EndsWith(".lnk", StringComparison.OrdinalIgnoreCase) || path.ToLowerInvariant().EndsWith(".url", StringComparison.OrdinalIgnoreCase))
```
Comment (gave92) [inline Files/Helpers/StorageHelpers.cs:26]: ToLowerInvariant() should now be redundant

File: Files/Helpers/StorageHelpers.cs [hunk 3]
```diff
@@ -11,58 +11,93 @@ namespace Files.Helpers
...
+                }
+                else if (typeof(IStorageItem).IsAssignableFrom(typeof(TRequested)))
+                {
+                    if (System.IO.Path.HasExtension(path)) // Possibly a file
                     {
-                        // It wasn't a folder, so check file then because it wasn't checked
                         await GetFile();
                     }
+                    
+                    if (!file || file.Result == null) // Possibly a folder
```
Comment (gave92) [inline Files/Helpers/StorageHelpers.cs:81]: Doesn't this throw NullReferenceException given that it's initialized as `FilesystemResult<BaseStorageFile> file = null;`?

File: Files/Helpers/StorageHelpers.cs [hunk 4]
```diff
@@ -11,58 +11,93 @@ namespace Files.Helpers
...
+                    {
+                        await GetFolder();
+
+                        if (file != null && (!folder || folder.Result == null))
```
Comment (gave92) [inline Files/Helpers/StorageHelpers.cs:85]: And this one maybe `if (file == null && !folder)` == "try file only if it was not tried before"

File: Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj [hunk 5]
```diff
@@ -30,43 +30,43 @@
     <VCProjectVersion>16.0</VCProjectVersion>
     <ProjectGuid>{A2FF3F3B-8EBC-4108-B99D-1476B7876656}</ProjectGuid>
     <Keyword>AtlProj</Keyword>
-    <WindowsTargetPlatformVersion>10.0.19041.0</WindowsTargetPlatformVersion>
+    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
```
Comment (gave92) [inline Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj:33]: Could we keep changes to this file (if necessary) to a separate PR?

Comment (yaichenbaum) [reply Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj:33]: Would be nice if GitHub had the option to split a PR 🤔

File: Files/Helpers/StorageHelpers.cs (hunk 3 above)
Comment (d2dyno1) [reply Files/Helpers/StorageHelpers.cs:81]: I've modified bool operator

File: Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj (hunk 5 above)
Comment (gave92) [reply Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj]: @d2dyno1 this is needed to compile on VS2022 I assume?

Comment (d2dyno1) [reply Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj]: VS adds them automatically, these don't prevent from building on VS2022.

File: Files/Helpers/NativeFileOperationsHelper.cs [hunk 6]
```diff
@@ -224,6 +224,9 @@ IntPtr lpOverlapped
             [In] ref NativeOverlapped lpOverlapped,
             LPOVERLAPPED_COMPLETION_ROUTINE lpCompletionRoutine);
 
+        [DllImport("api-ms-win-core-errorhandling-l1-1-1.dll")]
```
Comment (gave92) [inline Files/Helpers/NativeFileOperationsHelper.cs:227]: Not an issue but the docs for `Marshal.GetLastWin32Error()` state:
> This method exists because it is not reliable to make a direct platform invoke call to GetLastError to obtain this information. If you want to access this error code, you must call GetLastWin32Error instead of writing your own platform invoke definition for GetLastError and calling it.

So perhaps it's best to remove it before we use it improperly :)

Comment (d2dyno1) [reply Files/Helpers/NativeFileOperationsHelper.cs]: Didn't know it, thanks!

File: Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj (hunk 5 above)
Comment (gave92) [reply Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj]: Asking as I'm stuck on VS2019 and this changes do prevent _me_ from building =P

Comment (d2dyno1) [reply Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj]: Why won't you upgrade to VS2022? It builds fine for me

**Review by gave92 — APPROVED** [review]
LGTM

**Review by yaichenbaum — APPROVED** [review]
LGTM
