### PR TITLE
Fix edit tags & edit terminals buttons in settings

### LINKED ISSUE #6234: Edit File Tags button does not work
### Description

I click on the icon on the left to pop out another window, hopefully to be able to edit but it doesn't open.

### Steps To Reproduce

1. Go to settings
2. Click on Experimental
3. Enable File Tags
4. Then click on the icon that's to the left of "Edit file tags."

### Expected behavior

I expected it to open something like a new tab or play a video on how to edit the tags.

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1237

### Windows Version

21H1- Windows 10 Home

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #6234

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

File: Files/ViewModels/SettingsViewModels/ExperimentalViewModel.cs [hunk 1]
```diff
@@ -29,8 +31,20 @@ public bool AreFileTagsEnabled
 
         private async void LaunchFileTagsConfigFile()
```
Comment (d2dyno1) [inline Files/ViewModels/SettingsViewModels/ExperimentalViewModel.cs:32]: While at it, can you change it to `asnyc Task`?
Also:
```cs
public ICommand EditFileTagsCommand = new AsyncRelayCommand(LaunchFileTagsConfigFile);
```

**Review by d2dyno1 — APPROVED** [review]
Lgtm

**Review by BanCrash — APPROVED** [review]
LGTM
