### PR TITLE
Fix file extension being lost when renaming, fixes for search

### LINKED ISSUE #5823: Renaming issue on search results
### Description

When searching something then trying to rename it, it will say the extensions has been changed (even though it doesn't show in name or renaming) and when clicking ok it wont rename it.

### Steps To Reproduce

_No response_

### Expected behavior

It should show the extension, not bring up the warning unless renaming the extension, rename the file.

### Files Version

1.9.23.0

### Windows Version

10.0.19043.1151

### Relevant Assets

_No response_

### LINKED ISSUE #7012: When I rename a shortcut of a folder, it is no longer a shortcut file
### Description

When I rename a shortcut of a folder, it turns into an empty file which cannot jump to the correct space.

### Steps To Reproduce

1.Create a shortcut of a folder
2.Rename the shortcut
3.It occurs

### Expected behavior

It must correctly rename the shortcut

### Files Version

2.0.34.0

### Windows Version

Windows 11 21H2 22000.348

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #7012
- May fix #5823

**Details of Changes**
Add details of changes here.
- Fixes an issue where file extension is lost when renaming a shortcut to a folder
- Adds an ItemNameRaw property to ListedItem, moves the logic to get the "Display" name from the raw name into ListedItem and subclasses.
- Fixes an issue where file extensions where shown in Search result page regardless of the "show file extensions" setting
- Fixes an issue where search results were loaded twice when submitting search
- Fixes an issue where a file with a random name shows when search yields no results

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested renaming files and shortcuts changing the "show file extensions" setting

### CODE REVIEW

File: Files/Filesystem/Search/FolderSearch.cs [hunk 1]
```diff
@@ -204,7 +204,7 @@ private async Task SearchTagsAsync(string folder, IList<ListedItem> results, Can
                     return (hFileTsk, findDataTsk);
                 }).WithTimeoutAsync(TimeSpan.FromSeconds(5));
 
-                if (hFile != IntPtr.Zero)
+                if (hFile != IntPtr.Zero && hFile.ToInt64() != -1)
```
Comment (d2dyno1) [inline Files/Filesystem/Search/FolderSearch.cs:207]: Is `hFile != IntPtr.Zero` needed?

**Review by d2dyno1 — APPROVED** [review]

File: Files/Filesystem/Search/FolderSearch.cs (hunk 1 above)
Comment (gave92) [reply Files/Filesystem/Search/FolderSearch.cs:207]: Yeah because of the timeout above, if the timeout expires it returns the default value for an IntPtr which is IntPtr.Zero
