### PR TITLE
Search enhancements

### LINKED ISSUE #3348: Drag and Drop in Search mode
**Describe the bug**
Drag & Drop in Search mode not working.

**To Reproduce**
1. Go search for some files.
2. Click on random file.
3. Try to drag or drop file anywhere.

**Expected behavior**
In search mode I expected normal drag and drop behavior.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 1909 18363.1316
 - App version: [v1.1.0.0]

### LINKED ISSUE #3443: Auto suggestions when searching are imprecise
**Describe the bug**
When typing into the auto suggestion box, the suggestions might be totally unrelated to what I typed.

**To Reproduce**
Just search for something

**Expected behavior**
File names should contain the string I typed into the box

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS Version: 
Edition	Windows 10 Pro
Version	20H2
Installiert am	‎19.‎06.‎2020
Betriebssystembuild	19042.746
Leistung	Windows Feature Experience Pack 120.2212.551.0

 - App version: [v0.12.0]

### LINKED ISSUE #4231: Enhancement: Add a way to cancel a search
**Explain the bug**
There seems to be no way to cancel the search and the search seems to be going on forever.

**To reproduce**
1. Navigate to a folder
2. Search for something which is not in that folder

**Expected behavior**
Search should either be cancelable or should stop pretty quickly saying that no item with given name was found

https://user-images.githubusercontent.com/17484252/112075809-81357500-8b79-11eb-97bf-955d64251e80.mp4

### LINKED ISSUE #5813: Give some indication a search is in progress
### What's the Problem?

When I search something in a drive there's no indication its doing it. 

### Solution/Idea

When pressing enter for a search it would be better to show a blank screen and have the tab say Searching or "folder" search with the progress ring going, The blank area is were the content will appear.

### Alternatives

None

### Priorities

_No response_

### Files Version

1.9.23.0

### Windows Version

10.0.19043.1151

### Additional comment

_No response_

### LINKED ISSUE #5821: Enable refresh button on search results
### What's the Problem?

Currently I have to back out of search results then re search what I already did to get updated results

### Solution/Idea

Enable the refresh button to re search the folder for my search term

### Alternatives

None

### Priorities

_No response_

### Files Version

1.9.23

### Windows Version

10.0.19043.1151

### Additional comment

_No response_

### LINKED ISSUE #5831: F3 for search
### What's the Problem?

F3 key for launch search doesn't works

### Solution/Idea

Add F3 key for search

### Alternatives

f3 for search

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

1.9

### Windows Version

windows 11

### Additional comment

_No response_

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #5821
- Closes #4231 (back button, invoking a sidebar item, or otherwise navigating away will cancel the search)
- Closes #5813 
- Closes #5831
- Closes #3348
- Closes #3443
- related #2447

**Details of Changes**
Add details of changes here.
- make search more accurate by searching by filename instead of keywords (note: "$" is used to indicate advanced search and to not wrap in filename property)
- search items async
- show loading indicator while loading results
- allow refreshing search results
- allow cancelling search by navigating away
- allow dragging items in search results
- when no search results are found, show "no items found" instead of folder empty
other minor fixes:
- also fixes an issue where preview pane media controls would be too small
- fixes issue where trying to share a folder would cause the share flyout to crash
- improve thumbnails in details view by ThumbnailMode.SingleItem instead of ThumbnailMode.ListView
- fix issue where pressing open with overflow item with touch would unexpectedly close flyout

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**

https://user-images.githubusercontent.com/59544401/129529360-ef8667e0-e3e2-4f26-a268-c1c313f8821d.mp4

### CODE REVIEW

File: Files/Filesystem/Search/FolderSearch.cs [hunk 1]
```diff
@@ -31,26 +34,55 @@ internal class FolderSearch
...
+            get
+            {
+                // if the query starts with a $, assume the query is in aqs format, otherwise assume the user is searching for the file name
+                if (Query is not null && Query.StartsWith("$"))
+                {
+                    return Query.Substring(1);
+                }
+                else
+                {
+                    return $"filename:\"{Query}\"";
```
Comment (gave92) [inline Files/Filesystem/Search/FolderSearch.cs:50]: AQS query syntax is localized "filename:XXX" only works is system language is English. I think you have to use `System.Filename:XXX`.

File: Files/Filesystem/Search/FolderSearch.cs [hunk 2]
```diff
@@ -31,26 +34,55 @@ internal class FolderSearch
...
-        public async Task<ObservableCollection<ListedItem>> SearchAsync()
+        public EventHandler SearchTick;
+
+        public string AQSQuery
         {
-            var results = new ObservableCollection<ListedItem>();
+            get
+            {
+                // if the query starts with a $, assume the query is in aqs format, otherwise assume the user is searching for the file name
+                if (Query is not null && Query.StartsWith("$"))
```
Comment (gave92) [inline Files/Filesystem/Search/FolderSearch.cs:44]: I think this can be changed to `if (Query is not null && (Query.StartsWith("$") || Query.Contains(":")))`. Filenames don't contain ":" so if the user types ":" it's for sure AQS

File: Files/Views/ModernShellPage.xaml.cs [hunk 3]
```diff
@@ -281,6 +281,7 @@ private async void ModernShellPage_TextChanged(ISearchBox sender, SearchBoxTextC
             {
                 if (!string.IsNullOrWhiteSpace(sender.Query))
                 {
+                    var query = sender.Query;
```
Comment (gave92) [inline Files/Views/ModernShellPage.xaml.cs:284]: Same changes to be done to ColumnShellPage?

File: Files/Views/ModernShellPage.xaml.cs [hunk 4]
```diff
@@ -322,24 +323,32 @@ private void ModernShellPage_QuerySubmitted(ISearchBox sender, SearchBoxQuerySub
             }
         }
 
+        FolderSearch previousSearchInstance;
```
Comment (gave92) [inline Files/Views/ModernShellPage.xaml.cs:326]: Is this needed?

File: Files/Views/ModernShellPage.xaml.cs [hunk 5]
```diff
@@ -1167,6 +1189,7 @@ public class NavigationArguments
         public IShellPage AssociatedTabInstance { get; set; }
         public bool IsSearchResultPage { get; set; } = false;
         public ObservableCollection<ListedItem> SearchResults { get; set; } = new ObservableCollection<ListedItem>();
+        public FolderSearch FolderSearch { get; set; }
```
Comment (gave92) [inline Files/Views/ModernShellPage.xaml.cs:1192]: Is this used?

File: Files/BaseLayout.cs [hunk 6]
```diff
@@ -445,7 +445,7 @@ protected override async void OnNavigatedTo(NavigationEventArgs eventArgs)
             }
             else
             {
-                ParentShellPageInstance.NavToolbarViewModel.CanRefresh = false;
+                ParentShellPageInstance.NavToolbarViewModel.CanRefresh = true;
```
Comment (gave92) [inline Files/BaseLayout.cs:448]: For some reason it appears I can only refresh once, after that the button gets disabled.

File: Files/Views/ModernShellPage.xaml.cs (hunk 4 above)
Comment (winston-de) [reply Files/Views/ModernShellPage.xaml.cs:326]: yes the search instance is saved for easily refreshing search results by calling SearchAsync again with the same FolderSearch instance

Comment (gave92) [reply Files/Views/ModernShellPage.xaml.cs:326]: Soyry just seen the reference in `Refresh_Click` 👍

File: Files/BaseLayout.cs (hunk 6 above)
Comment (winston-de) [reply Files/BaseLayout.cs:448]: Thanks, should be fixed now

File: Files/Views/ModernShellPage.xaml.cs (hunk 5 above)
Comment (winston-de) [reply Files/Views/ModernShellPage.xaml.cs]: no, removed

**Comment by gave92** [comment]
Ups sorry I force pushed 😅 hope it does not cause issues for you.

**Comment by winston-de** [comment]
> Ups sorry I force pushed 😅 hope it does not cause issues for you.

all good

**Comment by gave92** [comment]
I think I'm done xD please let me know if you agree with the changes.

**Comment by yaichenbaum** [comment]
> improve thumbnails in details view by ThumbnailMode.SingleItem instead of ThumbnailMode.ListView

@gave92 does this have any performance or speed impact?

**Comment by winston-de** [comment]
> > improve thumbnails in details view by ThumbnailMode.SingleItem instead of ThumbnailMode.ListView
> 
> @gave92 do you know if this has any performance or speed impact?

I tested in release mode, there's no noticeable difference in loading speed.

**Comment by winston-de** [comment]
> I think I'm done xD please let me know if you agree with the changes.

They're great, thank you

**Comment by winston-de** [comment]
currently there isn't a way to view the query after searching, what if it was shown in the path box like this?
image

**Comment by yaichenbaum** [comment]
> currently there isn't a way to view the query after searching, what if it was shown in the path box like this?
> image

That would be helpful.

**Comment by yaichenbaum** [comment]
@winston-de can you reproduce an issue where icons are loading with wrong size in some locations?
image

**Comment by winston-de** [comment]
Yes, but it seems to be a windows issue as I can repro in explorer as well for the same items. Is it just in files for you?

File: Files/ViewModels/ItemViewModel.cs [hunk 7]
```diff
@@ -819,9 +819,7 @@ private async Task LoadItemThumbnail(ListedItem item, uint thumbnailSize = 20, I
                         var matchingStorageFolder = (StorageFolder)matchingStorageItem ?? await GetFolderFromPathAsync(item.ItemPath);
                         if (matchingStorageFolder != null)
                         {
-                            var mode = thumbnailSize < 80 ? ThumbnailMode.ListView : ThumbnailMode.SingleItem;
```
Comment (winston-de) [inline Files/ViewModels/ItemViewModel.cs:822]: I noticed this change will make it try and show previews, which isn't useful since it's so small. Should this e reverted?
image

Comment (winston-de) [reply Files/ViewModels/ItemViewModel.cs:822]: also, @gave92 you were right xD. It looks like ThumbnailOptions.ResizeThumbnail is the better option. `UseCurrentScale` won't use smaller icons like this one
image

**Review by gave92 — APPROVED** [review]
Great work 👍

**Comment by gave92** [comment]
> > currently there isn't a way to view the query after searching, what if it was shown in the path box like this?

Could we avoid to clear the search box instead?

File: Files/ViewModels/ItemViewModel.cs (hunk 7 above)
Comment (yaichenbaum) [reply Files/ViewModels/ItemViewModel.cs:822]: Does Resize cut off the thumbnail?

**Comment by yaichenbaum** [comment]
Great work!
