### PR TITLE
Fix new context menu

### LINKED ISSUE #5332: Crash when opening log folder
**Explain the bug**
As the title says another thing is that the log files rapidly appear and disappear before crashing.

**To reproduce**
1. Go to Settings
2. Click on About
3. Click on Open logs
4. Wait a bit
5. see "Something when wrong" notifications 

**Expected behaviour**
Shouldn't crash

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6721993/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6721994/debug_fulltrust.log)

**System Information**
 - OS Version: Windows 10 21H1 19043.1088
 - App version: v1.5,46

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Fixes #5332

**Changes**
- Fixes an issue introduced in #5242 which affects the "new" menu and folder empty-space menu
- Fixes an issue with the filewatcher for which a crash can occur when temp files are quickly created/deleted
- Fixes an issue with the selection rectangle for which a crash can occur when temp files are quickly created/deleted

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

File: Files/ViewModels/ItemViewModel.cs [hunk 1]
```diff
@@ -41,7 +41,7 @@ public class ItemViewModel : INotifyPropertyChanged, IDisposable
         private readonly SemaphoreSlim enumFolderSemaphore = new SemaphoreSlim(1, 1);
         private readonly SemaphoreSlim loadExtendedPropsSemaphore = new SemaphoreSlim(Environment.ProcessorCount, Environment.ProcessorCount);
         private readonly ConcurrentQueue<(uint Action, string FileName)> operationQueue = new ConcurrentQueue<(uint Action, string FileName)>();
-        private readonly SemaphoreSlim operationSemaphore = new SemaphoreSlim(1, 1);
+        private readonly ManualResetEventSlim operationEvent = new ManualResetEventSlim();
```
Comment (duke7553) [inline Files/ViewModels/ItemViewModel.cs:44]: Great work. Can you explain how ManualResetEventSlim would improve things here?

Comment (gave92) [reply Files/ViewModels/ItemViewModel.cs:44]: It's not mandatory to switch from Semaphore  to ManualResetEvent. But in my mind Semaphore is for controlling access to a shared resource, while here we use it to signal that an item has been added to the queue (looks like an event job).

Also it simplifies code a little:
```cs
try {
operationSemaphore.Release();
} catch (Exception)
{
// Prevent semaphore handles exceeding
}
```
To:
```cs
operationEvent.Set();
```

**Review by winston-de — APPROVED** [review]
