### PR TITLE
Fixed an issue where changing the theme settings wasn't working correctly

### LINKED ISSUE #3291: Theme mode returns to "Windows Default" when restarting the app
When I change the theme mode then I close and open the app again, it is back to "Windows default"
_Nothing useful in the log_

theme

### PR DESCRIPTION
**Pull request by AndyMDoyle**
Fixes #3291

Sorry, my bad.

I didn't realise that ThemeHelper was setting the theme on elements by capturing a reference to the MainPage. I assumed it was relying on Application.RequestedTheme and changing this.

Balance is restored, and ThemeHelper has had some unused code removed. ThemeHelper.RootTheme has been refactored slightly to make it responsible for reading the value from one place (LocalSettings), and setting ThemeHelper.RootTheme will persist this change back to LocalSettings and call ApplyTheme() to have the current theme applied across the application.

### CODE REVIEW

File: Files/Helpers/ThemeHelper.cs [hunk 1]
```diff
@@ -99,31 +62,32 @@ private static async void UiSettings_ColorValuesChanged(UISettings sender, objec
...
+            if (Window.Current.Content is FrameworkElement rootElement)
+            {
+                rootElement.RequestedTheme = rootTheme;
+            }
+
+            switch (rootTheme)
             {
                 case ElementTheme.Default:
                     App.AppSettings.AcrylicTheme.SetDefaultTheme();
-                    titleBar.ButtonHoverBackgroundColor = (Color)Application.Current.Resources["SystemBaseLowColor"];
```
Comment (tsvietOK) [inline Files/Helpers/ThemeHelper.cs:113]: Check titlebar buttons color.
image

Comment (yaichenbaum) [reply Files/Helpers/ThemeHelper.cs:113]: @AndyMDoyle It looks like the code to set the title bar buttons color was removed in one of your commits.

**Review by tsvietOK — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@AndyMDoyle Thank you!
