### PR TITLE
Fixed DynamicDialog background and fixed an issue when creating a Bundle

### LINKED ISSUE #3269: [Bug] UI bugs with Bundles widget
##  **Describe the bug**
UI Bugs in version 1.1.5.0
### 1.
When I create a bundle (from the big + icon), type in the name and press enter, I get input field empty warning. (the input isn't empty)

### 2.
When I create a bundle from the right side three dots, the popup is out of theme. (I'm using dark theme in the app and light in windows)

### 1.
Make a bundle without any warning.

### 2.
Dark theme poup.

### 1.
iuzlokftzgduj

### 2.
ghjzfvljuh

## **Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.746]
 - App version: [v1.1.5.0]
 
**Log file**
Nothing suspicious.

### PR DESCRIPTION
**Pull request by d2dyno1**
Closes #3269

### CODE REVIEW

File: Files/ViewModels/Bundles/BundlesViewModel.cs [hunk 1]
```diff
@@ -105,6 +105,7 @@ private void InputTextKeyDown(KeyRoutedEventArgs e)
         {
             if (e.Key == VirtualKey.Enter)
             {
+                OnPropertyChanged(nameof(BundleNameTextInput)); // Update the property text
```
Comment (tsvietOK) [inline Files/ViewModels/Bundles/BundlesViewModel.cs:108]: `UpdateSourceTrigger=PropertyChanged` is enough in XAML, no need to add `OnPropertyChanged`.

Comment (d2dyno1) [reply Files/ViewModels/Bundles/BundlesViewModel.cs]: Thanks! Good to know!

**Review by tsvietOK — APPROVED** [review]
